import type { Customer, PreCheckRecord, ParameterRecord, PostObservationRecord, AbnormalReport, HandoverLog } from './types';

const NOW = Date.now();

export const mockCustomers: Customer[] = [
  {
    id: 'C001',
    name: '张晓红',
    gender: '女',
    age: 32,
    phone: '138****2345',
    checkInTime: '09:15',
    appointment: '光子嫩肤（全脸）',
    doctor: '李医生',
    status: 'completed',
    treatmentPlan: '全脸 DPL 嫩肤，能量 15-18J/cm²，脉宽 10-15ms，3遍',
    planUpdatedAt: NOW - 86400000,
    planAuthor: '李医生',
    photoRequired: false,
    needsDoctorReview: false,
  },
  {
    id: 'C002',
    name: '王美丽',
    gender: '女',
    age: 28,
    phone: '139****6789',
    checkInTime: '09:40',
    appointment: '光子嫩肤（祛斑）',
    doctor: '李医生',
    status: 'observing',
    treatmentPlan: '双颊+鼻部针对性祛斑，能量 16-20J/cm²，脉宽 12-18ms',
    planUpdatedAt: NOW - 7200000,
    planAuthor: '李医生',
    photoRequired: true,
    needsDoctorReview: false,
  },
  {
    id: 'C003',
    name: '刘建国',
    gender: '男',
    age: 45,
    phone: '137****0123',
    checkInTime: '10:05',
    appointment: '光子嫩肤（红血丝）',
    doctor: '陈医生',
    status: 'treating',
    treatmentPlan: '双颊红血丝区，低能量多次，能量 12-15J/cm²，脉宽 20-30ms',
    planUpdatedAt: NOW - 5400000,
    planAuthor: '陈医生',
    photoRequired: false,
    needsDoctorReview: true,
  },
  {
    id: 'C004',
    name: '陈丽娜',
    gender: '女',
    age: 36,
    phone: '136****4567',
    checkInTime: '10:30',
    appointment: '光子嫩肤（全脸+颈部）',
    doctor: '李医生',
    status: 'checking',
    treatmentPlan: '全脸+颈部嫩肤，能量 14-17J/cm²，脉宽 10-15ms，2-3遍',
    planUpdatedAt: NOW - 3600000,
    planAuthor: '李医生',
    photoRequired: true,
    needsDoctorReview: false,
  },
  {
    id: 'C005',
    name: '赵敏',
    gender: '女',
    age: 29,
    phone: '135****8901',
    checkInTime: '10:55',
    appointment: '光子嫩肤（痤疮）',
    doctor: '陈医生',
    status: 'waiting',
    photoRequired: false,
    needsDoctorReview: false,
  },
  {
    id: 'C006',
    name: '孙芳',
    gender: '女',
    age: 41,
    phone: '134****2345',
    checkInTime: '11:20',
    appointment: '光子嫩肤（抗衰）',
    doctor: '李医生',
    status: 'waiting',
    photoRequired: false,
    needsDoctorReview: false,
  },
  {
    id: 'C007',
    name: '周强',
    gender: '男',
    age: 38,
    phone: '133****6789',
    checkInTime: '13:30',
    appointment: '光子嫩肤（毛孔粗大）',
    doctor: '陈医生',
    status: 'waiting',
    photoRequired: true,
    needsDoctorReview: false,
  },
];

export const mockPreChecks: PreCheckRecord[] = [
  {
    customerId: 'C001',
    version: 1,
    createdAt: NOW - 600000,
    timestamp: '09:20',
    nameVerified: true,
    treatmentSites: ['额头', '左颊', '右颊', '鼻部', '下颌'],
    contraindications: [],
    recentSunExposure: '无',
    medicationUse: '无特殊用药',
    planReviewed: true,
    operator: '治疗师-王',
  },
  {
    customerId: 'C001',
    version: 2,
    createdAt: NOW - 540000,
    timestamp: '09:21',
    nameVerified: true,
    treatmentSites: ['额头', '左颊', '右颊', '鼻部', '下颌', '颈部'],
    contraindications: [],
    recentSunExposure: '轻度',
    medicationUse: '无特殊用药，昨日服用维生素C',
    planReviewed: true,
    operator: '治疗师-王',
  },
];

export const mockParameters: ParameterRecord[] = [
  {
    customerId: 'C001',
    version: 1,
    createdAt: NOW - 480000,
    timestamp: '09:35',
    deviceModel: 'DPL 精准嫩肤仪 Pro',
    treatmentHead: '500-600nm 嫩肤治疗头',
    energy: '16J/cm²',
    pulseWidth: '12ms',
    spotSize: '15×50mm',
    passes: 3,
    operator: '治疗师-王',
    remark: '初设参数',
  },
  {
    customerId: 'C001',
    version: 2,
    createdAt: NOW - 420000,
    timestamp: '09:37',
    deviceModel: 'DPL 精准嫩肤仪 Pro',
    treatmentHead: '500-600nm 嫩肤治疗头',
    energy: '18J/cm²',
    pulseWidth: '12ms',
    spotSize: '15×50mm',
    passes: 3,
    operator: '治疗师-王',
    remark: '双颊能量调整至 18J/cm²，患者耐受良好',
  },
];

export const mockObservations: PostObservationRecord[] = [
  {
    customerId: 'C002',
    startTime: '10:50',
    duration: 1200,
    startTimestamp: NOW - 1200 * 1000,
    pauseStart: null,
    pausedDuration: 0,
    timeline: [
      { type: 'start', timestamp: NOW - 1200 * 1000, label: '开始观察', operator: '治疗师-王' },
      { type: 'care_cold', timestamp: NOW - 1100 * 1000, label: '完成冷敷', detail: '医用冷敷贴 15 分钟', operator: '治疗师-王' },
      { type: 'save', timestamp: NOW - 600 * 1000, label: '暂存记录', detail: '已记录分区反应', operator: '治疗师-王' },
      { type: 'care_sunscreen', timestamp: NOW - 300 * 1000, label: '完成防晒叮嘱', operator: '治疗师-王' },
    ],
    areaReactions: [
      { area: '左颊', redness: '轻度', burning: '轻微', remark: '有温热感' },
      { area: '右颊', redness: '轻度', burning: '轻微' },
      { area: '鼻部', redness: '中度', burning: '轻微', remark: '局部微红' },
      { area: '额头', redness: '无', burning: '无' },
      { area: '下颌', redness: '轻度', burning: '轻微' },
    ],
    coldCompressDone: true,
    repairMaskDone: false,
    sunscreenAdviceDone: true,
    operator: '治疗师-王',
    completed: false,
  },
];

export const mockAbnormalReports: AbnormalReport[] = [
  {
    id: 'ABN001',
    customerId: 'C003',
    customerName: '刘建国',
    timestamp: '10:15',
    type: 'severePain',
    typeLabel: '强烈疼痛',
    severity: '中度',
    description: '患者诉右颊治疗中疼痛明显，VAS评分6分',
    handling: '已降低能量至12J/cm²，局部冷敷处理，疼痛缓解',
    reportedBy: '治疗师-王',
    reviewed: false,
  },
];

export const mockHandoverLogs: HandoverLog[] = [
  {
    id: 'HO001',
    timestamp: '2026-06-21 18:00',
    shiftOperator: '治疗师-王',
    nextOperator: '治疗师-李',
    unfinishedObservations: ['C002 王美丽'],
    photosPending: ['C002 王美丽', 'C004 陈丽娜'],
    doctorReviews: ['C003 刘建国'],
    abnormalReports: ['ABN001 刘建国-强烈疼痛'],
    remark: '注意C003治疗后观察',
  },
];
